# local 테스트 용

spring:
  security:
    debug: true
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=AvailManage;encrypt=true;trustServerCertificate=true;
    username: wppis_user
    password: unison
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        security: TRACE

server:
  port: 6789
  servlet:
    session:
      timeout: 43200

## custom setting
unlock-cors:
  ip: localhost
  port: 5151
  domain: jeongam.scada.unison.co.kr

wind-farm:
  turbines-number: 3
  total-exported-power-name: U136_WTUR_TotWh

opc:
  server-name: BACHMANN.OPCStandardServer
  prefix-format: WindFarm.WTG%02d.