spring:
  security:
    debug: true
    user:
      name: user
      password: 1234
      roles: USER


logging:
  level:
    org:
      springframework:
        security: TRACE

server:
  port: 6789

---
spring:
  profiles:
    active: prod

---
spring:
  profiles:
    active: dev