INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_USER', 'kim garden', CURRENT_TIMESTAMP());
INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon2@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_MANAGER', 'kim jae woo', CURRENT_TIMESTAMP());
INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon3@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_ADMIN', 'kim won', CURRENT_TIMESTAMP());
INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon4@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_USER', 'kim garden', CURRENT_TIMESTAMP());
INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon5@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_MANAGER', 'kim jae woo', CURRENT_TIMESTAMP());
INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon6@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_ADMIN', 'kim won', CURRENT_TIMESTAMP());
INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon7@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_USER', 'kim garden', CURRENT_TIMESTAMP());
INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon8@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_MANAGER', 'kim jae woo', CURRENT_TIMESTAMP());
INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon9@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_ADMIN', 'kim won', CURRENT_TIMESTAMP());
INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon10@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_USER', 'kim garden', CURRENT_TIMESTAMP());
INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon11@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_MANAGER', 'kim jae woo', CURRENT_TIMESTAMP());
INSERT INTO users (id, pw, role, name, created_at) VALUES ('kjwon12@unison.co.kr', '$2a$12$Vxiv/v2kiznDm1QmQv6fVO8bIrqNiChKWOQeV4Ke0l4vvLEQ0mdvm', 'ROLE_ADMIN', 'kim won', CURRENT_TIMESTAMP());
